noinst_PROGRAMS = \
	test-bsoncpp \
	test-mongocpp

AM_CPPFLAGS = \
	-I $(top_srcdir)/lib

test_bsoncpp_SOURCES = $(top_srcdir)/tests/test-bsoncpp.cpp

test_mongocpp_SOURCES = $(top_srcdir)/tests/test-mongocpp.cpp

LDADD = \
   libbsoncpp.la \
   libmongocpp.la
